### ISSUE TITLE
Floating label and underline do not get invalid class

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-theme-material#12]
When entering invalid value to input the floating label and underline need to be assigned an invalid css class:

![49769d51-a3b3-42cb-a96c-f72db7c8e96c_angular-validaton](https://user-images.githubusercontent.com/20015190/32175345-59d70e5a-bd8d-11e7-80e3-28ad9ae0a22e.png)

**Comment by gyoshev** [comment]
Fixed by upgrading to `@progress/kendo-angular-inputs@1.3.3` and `@progress/kendo-theme-material@0.2.4` -- [plunker snippet](http://plnkr.co/edit/fot7bVg7fJKksOD53x6D?p=preview).
