### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by General-Afify** [telerik/kendo-theme-material#13]
Hi,

When importing the theme using:
@import "node_modules\\@progress\kendo-theme-material\scss\all";
The below error appears:

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: node_modules\\@progress\kendo-theme-material/modules\\@progress\kendo-theme-default\scss\mixins\_button.scss
Error: ".k-button:not(.k-no-focus):focus" failed to @extend "%appearance_focused-button".
       The selector "%appearance_focused-button" was not found.
       Use "@extend %appearance_focused-button !optional" if the extend should be able to fail.
        on line 62 of node_modules\\@progress\kendo-theme-material\modules\@progress\kendo-theme-default\scss\mixins\_button.scss
>> mixin appearance_focused-button { @extend %appearance_focused-button };
   ------------------------------------------^

**Comment by gyoshev** [comment]
We are not aware of this problem, and I could not reproduce this in Angular-CLI. Please [open a support ticket](https://www.telerik.com/account/support-tickets) and provide a sample project that illustrates the problem.
