### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by lifeinchords** [telerik/kendo-theme-material#15]
Hi,

I'm still transitioning from .less based themes to Sass. 
The new docs are great, and apparently the `.all` file is what I need for the common + theme. Does that include mobile support too, that I would've found from one of these files:
`https://kendo.cdn.telerik.com/2017.2.504/styles/kendo.material.mobile.min.css`

Any thoughts appreciated

**Comment by gyoshev** [comment]
@lifeinchords yes, the single file includes also these styles. However, at the time of writing, the material theme is still in an early preview, so these styles are not included. At this time, [consider using the Default theme](https://github.com/telerik/kendo-theme-default).

**Comment by lifeinchords** [comment]
Thanks for the update - will do.
